create database QuanLyDiemThi;
CREATE TABLE HocSinh(
	MaHS VARCHAR(20) PRIMARY KEY,
    TenHS VARCHAR(50),
    NgaySinh DATETIME,
    Lop VARCHAR(20),
    GT VARCHAR(20)
);

CREATE TABLE MonHoc(
	MaHS VARCHAR(20) PRIMARY KEY,
    TenMH VARCHAR(50)
);

ALTER TABLE MonHoc rename column MaHS to MaMH;

CREATE TABLE BangDiem(
	MaHS VARCHAR(20),
    MaMH VARCHAR(20),
    DiemThi INT,
    NgayKT DATETIME,
    PRIMARY KEY (MaHS, MaMH),
    FOREIGN KEY (MaHS) REFERENCES HocSinh(MAHS),
    FOREIGN KEY (MaMH) REFERENCES MonHoc(MAMH)
);

CREATE TABLE GiaoVien(
	MaGV VARCHAR(20) PRIMARY KEY,
    TenGV VARCHAR(20),
    SDT VARCHAR(10)
);

ALTER TABLE MonHoc ADD MaGV VARCHAR(20);
ALTER TABLE MonHoc ADD CONSTRAINT MaGV_FK FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV);
